name: easy_app_sreen_reports
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.18
  carousel_slider: ^5.0.0

  ui_style:
    git:
      url: https://github.com/corp-ais/mychannel-new-easy-app-2.00-ui-style.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/home.png
    - assets/icons/arrow_back.png
    - assets/icons/icon_people.png
    - assets/images/AIS-12C.png
    - assets/images/AIS-LOGO.png
    - assets/images/chm.iconillus_primary.png
    - assets/images/emblem_v2.png
    - assets/images/emblem.png
    - assets/coin_icon.png
    - assets/icons/icon_info_gray.png

  fonts:
    - family: DB_HelvethaicaAIS
      fonts:
      - asset: assets/fonts/DB_HelvethaicaAIS_X_v3.2.ttf
        weight: 400
      - asset: assets/fonts/DB_HelvethaicaAIS_X_Bd_v3.2.ttf
        weight: 700
        style: normal